version: '3.9'
services:
  ascout-client:
    build:
      context: ./ascout-client/
      dockerfile: ./config/local/Dockerfile
    ports:
      - "3000:3000"
    container_name: ascout-client
  calculator-service:
    build:
      context: ./calculator-service/
      dockerfile: ./config/local/Dockerfile
    ports:
      - "3001:3001"
    container_name: calculator-service
  browse-service:
    build:
      context: ./browse-service/
      dockerfile: ./config/local/Dockerfile
    ports:
      - "3002:3002"
    container_name: browse-service