apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ascout-client
  name: ascout-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascout-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ascout-client
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        name: ascout-client
      restartPolicy: Always
